import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ramadan
 */
public class PilotTaskMessage extends javax.swing.JFrame {

    /**
     * Creates new form PilotTask
     */
	
	static JFrame f1;
    public PilotTaskMessage() {
        initComponents();
    }

    public static int briefingCloseButtonPressed=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	// TODO Auto-generated method stub
		
    			//////***********************************
    			
    			 String briefingText="";
    		        
    		        String scenarioPath = JarPath.getClassPath() +"scenarios//";
    		        //	        ArrayList<String> briefing= loadBriefing(scenarioPath+Sea.scenarioName);

    		        ArrayList<String> briefing= loadBriefing(scenarioPath+Sea.scenarioName);
    		        briefingText = briefingText + briefing.get(1);
    		       
    		        
    		   //     taskTextPane.setEditable(false);
    		        
    		      
    		        BufferedImage image =  null;  
    		        try {
    					image = Utilities.getScaledImage(ImageIO.read(new File("images/"+briefing.get(0))),Integer.parseInt(briefing.get(2)),Integer.parseInt(briefing.get(3)));
    				} catch (NumberFormatException e) {
    					// TODO Auto-generated catch block
    					e.printStackTrace();
    				} catch (IOException e) {
    					// TODO Auto-generated catch block
    					e.printStackTrace();
    				}
    		       
    		        ImageIcon icon = new ImageIcon(image);
    			
    			
    			
    			
    		//*******************************************************************************	
    			
    		JButton close = new JButton("Close");
    		JTextArea text= new JTextArea();
    		//ImageIcon icon = new ImageIcon("battleship.png");
    		//Image image = icon.getImage(); // transform it 
//    		Image newimg = image.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
    		//icon = new ImageIcon(newimg); 
    		JLabel label = new JLabel(icon);
    		text.append(briefingText);
    		text.setLineWrap(true);
    		
    		 text.setEditable ( false ); // set textArea non-editable
    		    JScrollPane scroll = new JScrollPane ( text );
    		    scroll.setVerticalScrollBarPolicy ( ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    		    scroll.setHorizontalScrollBarPolicy ( ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

    		JPanel butn = new JPanel();
    		butn.setLayout(new FlowLayout());
    		butn.add(close);
    		
    		

    		JPanel rightpanel = new JPanel();
    		rightpanel.setLayout(new BorderLayout());
    		rightpanel.add(scroll,BorderLayout.CENTER);
    		rightpanel.add(butn,BorderLayout.SOUTH);
    		

    		
    		 JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
    		 splitPane.setResizeWeight(0.99);
    	     splitPane.setEnabled(false);
    	     splitPane.setDividerSize(0);
    	     splitPane.setDividerLocation(1010);
    	     splitPane.setOrientation(JSplitPane.HORIZONTAL_SPLIT);
    	     splitPane.setRightComponent(rightpanel);
    	     splitPane.setLeftComponent(label);
    		
    	     JPanel content = new JPanel();
    		 content.setLayout(new BorderLayout());
    	     content.add(splitPane, BorderLayout.CENTER);
    		
    		f1 = new JFrame();
    		//f1.setDefaultCloseOperation(f1.setVisible(false));
    		
    		f1.getContentPane();
    		
    		f1.setContentPane(content);
    		f1.pack();
    		f1.setSize(1379,765);
    		f1.setResizable(false);
    		f1.setLocationRelativeTo(null);
    		//f1.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    		//f1.setUndecorated(true);
    		f1.setVisible(true);
    		f1.setTitle("Pilot Task Instructions");
    		
    		close.addActionListener(new java.awt.event.ActionListener() {
    	        public void actionPerformed(java.awt.event.ActionEvent evt) {
    	            closeActionPerformed(evt);
    	        }
    	    });

    			
    			
    		}
    		private static void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    	        // TODO add your handling code here:
    	    	briefingCloseButtonPressed+=1;
    		
    	    	f1.setVisible(false);
    			
    	    }
    
    ArrayList<String> loadBriefing (String scenarioFileName){
	
	
	ArrayList<String> briefing = new ArrayList<String>();
	
	String imagepath="";
	String imagetext="";
	String sizeX="";
	String sizeY="";
	
	try {

		//JarPath.getClassPath().replace('\', '\\');
				
		DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
		Document document = documentBuilder.parse(scenarioFileName);
		document.getDocumentElement().normalize();
		
		NodeList nList = document.getElementsByTagName("img");

		for (int i = 0; i < nList.getLength(); i++) {

			
			Node nNode = nList.item(i);
			
			if (nNode.getNodeType() == Node.ELEMENT_NODE) {

				Element eElement = (Element) nNode;
					
			imagepath = eElement.getAttribute("src");
			imagetext = eElement.getAttribute("text");
			sizeX=eElement.getAttribute("sizeX");
			sizeY = eElement.getAttribute("sizeY");
			
			briefing.add(imagepath);
			briefing.add(imagetext);
			briefing.add(sizeX);
			briefing.add(sizeY);
	    //	System.out.println("dtada in breifing message windoe"+ briefing.get(0));
	    	
	    	
	    	 
	    	}
		} // finish looping on node list
		
		
	} catch (Exception pce) {
		pce.printStackTrace();
	}
	return briefing; 
	}
	

	
	
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
         Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
       

         Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilotTask().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane taskTextPane;
    // End of variables declaration//GEN-END:variables
}


